-- =========================================================
-- FACULTY REGISTRATION TABLE SCHEMA
-- Ramco Institute of Technology — CSBS Placement Portal
-- Compatible with MySQL and Supabase / PostgreSQL
-- =========================================================

-- ---------------------------------------------------------
-- 1. MySQL DDL
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS faculty_registration (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    mobile VARCHAR(15) NOT NULL,
    gender ENUM('Male', 'Female', 'Other', 'Prefer not to say') NOT NULL,
    department VARCHAR(150) NOT NULL,
    designation VARCHAR(100) NOT NULL,
    experience DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    qualification VARCHAR(200) NOT NULL,
    specialization VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'FACULTY',
    status ENUM('Pending', 'Active', 'Rejected') DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_faculty_email (email),
    INDEX idx_faculty_status (status)
);

-- ---------------------------------------------------------
-- 2. Supabase / PostgreSQL DDL
-- ---------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS public.faculty_registration (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     name TEXT NOT NULL,
--     email TEXT NOT NULL UNIQUE,
--     mobile TEXT NOT NULL,
--     gender TEXT NOT NULL,
--     department TEXT NOT NULL,
--     designation TEXT NOT NULL,
--     experience NUMERIC(4,1) NOT NULL DEFAULT 0,
--     qualification TEXT NOT NULL,
--     specialization TEXT NOT NULL,
--     password TEXT NOT NULL,
--     role TEXT DEFAULT 'FACULTY',
--     status TEXT DEFAULT 'Pending',
--     created_at TIMESTAMPTZ DEFAULT NOW(),
--     updated_at TIMESTAMPTZ DEFAULT NOW()
-- );

-- ALTER TABLE public.faculty_registration DISABLE ROW LEVEL SECURITY;
