-- ==========================================================
-- 3NF Department Normalization Migration for Supabase (PostgreSQL)
-- Project: Department Placement Portal
-- ==========================================================

-- Step 1: Create departments table in 3rd Normal Form
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code TEXT UNIQUE NOT NULL,
    department_name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security on departments so public/service role can access
ALTER TABLE public.departments DISABLE ROW LEVEL SECURITY;

-- Step 2: Seed the official CSBS department record (id = 1)
INSERT INTO public.departments (id, department_code, department_name)
VALUES (1, 'CSBS', 'Computer Science and Business Systems')
ON CONFLICT (id) DO UPDATE 
SET department_code = EXCLUDED.department_code,
    department_name = EXCLUDED.department_name;

-- Step 3: Add foreign key department_id column to users table
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES public.departments(id);

-- Step 4: Populate department_id for existing records
UPDATE public.users 
SET department_id = 1 
WHERE department_id IS NULL;

-- Step 5: (DESTRUCTIVE CHANGE - TO BE EXECUTED ONLY AFTER VERIFICATION)
-- Drops the old redundant department text column from the users table.
-- ALTER TABLE public.users DROP COLUMN IF EXISTS department;
